### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by ezamp** [partkeepr/PartKeepr#1009]
Hello,

I get this error when setting up the database:
Setting up the default footprints   ->   Invalid response from server

![capture](https://user-images.githubusercontent.com/388509/47355036-9fed6400-d6c0-11e8-9c2b-6a77d06dd227.JPG)
![error1](https://user-images.githubusercontent.com/388509/47354967-6f0d2f00-d6c0-11e8-8c92-1076407c8f67.JPG)
![error2](https://user-images.githubusercontent.com/388509/47354968-6fa5c580-d6c0-11e8-8b3a-533b5a83a926.JPG)

# System Information
* PartKeepr Version: 1.4.0 and 1.2.0
* DBMS: mysql

# How to reproduce
Perform a new installation

**Comment by mindsolve** [comment]
Hey @ezamp,
This error means that the `bcmath` PHP extension is not installed or not active.
Due to the fact that you did neither specify your server OS nor your webserver (apache/nginx) I can only thell you to install the bcmath extension.

On Debian and Ubuntu the package is either called php-bcmath or php<version>-bcmath (e.g. php7.0-bcmath)

**Comment by Drachenkaetzchen** [comment]
I have merged the pull request which should now fix the issue.
