### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by sbeaudoin** [partkeepr/PartKeepr#1013]
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr 1.4.0
* Ubuntu Desktop 18.04.1 as an Hyper-V VM.

# How to reproduce

- Install the docker image of partKeepr on ubuntu desktop.
- Install mysql.
- Access to the setup page of partkeepr in a browser.
- Follow the process up to the page asking for the database parameters.
- Make sur the fields of the web page are : hostname=localhost, name=partkeepr, user=partkeepr, port=3306, enter a custom password.
- Check the "show commands" checkbox and execute them in a terminal on the virtual machine.
- Click next.

# What Happend

The "Testing for database connectivity" fail with error "An exception occured in driver : SQLSTATE[HY000] [2002] No such file or directory".

**Comment by Gasman2014** [comment]
Are you able to connect to MySQL from the command line or do you get the same error? Try ‘mysql -u”username” - p’. This may mean that MySQL can’t get a lock file and may not be related to Partkeepr.

**Comment by sbeaudoin** [comment]
Yes, I am able to connect from the command line using the account partkeepr and the password specified in the setup web page.

**Comment by mindsolve** [comment]
Hey!
Could you, just as a test, replace the `localhost` with `127.0.0.1` in the hostname field?

As far as I remember, when having `localhost` as the database host, PHP / PDO is trying to connect to MySQL via the socket file, which may be inaccessable or at a different location.
Using 127.0.0.1 tries to connect also to the "localhost" but this time via network.

**Comment by sbeaudoin** [comment]
Uninstalled partkeepr and mysql dockers.  Reinstalled them.  Created the mysql database 'partkeepr' and user 'partkeepr' with grant all.  Now, at the database parameters page, either with localhost or 127.0.0.1 it says "An exception occured in driver: SQLSTATE[HY000][2003] Connection refused" at the "Setup 1/2" page.

**Comment by sbeaudoin** [comment]
The creation query reads (with password redacted) : 

```
CREATE DATABASE partkeepr CHARACTER SET UTF8;
GRANT USAGE ON *.* TO partkeepr@localhost IDENTIFIED BY 'myPassword';
GRANT ALL PRIVILEGES ON partkeepr.* to partkeepr@localhost;
```
Naturally, if I replace localhost with 127.0.0.1, it does the same replacements in the query.

**Comment by nhendin** [comment]
This is just a guess --- came here looking for ideas on another issue, but  as you noted earlier, could your firewall rules be blocking access to 127.0.0.1:3306?  
You could try:
`ufw disable`   {assuming you don't mind turning off the firewall for one minute or so}
test it and if it works, re-enable with 
`ufw enable`
Then set up the correct rules to allow access from <web server ip> to  <mysql server ip> on port 3306.
Please don't leave it disabled for too long though.

**Comment by sbeaudoin** [comment]
Thank you for the comment, but all this happen on the same machine.  So, the firewall is not implicated.

**Comment by mindsolve** [comment]
I think I know why this happens:
MySQL/MariaDB server on your Ubuntu VM is configured to only allow access from localhost, not other hosts in the network.
The Docker container with partkeepr running in it is "another host in a network", the docker0 network.
If you try to connect to localhost on the docker image, it won't work because no mysql is running in the docker image.

**Solution:**
If you start the image with the option `--network="host"`, the docker image will appear as if it was running on the host and then you can simply use `127.0.0.1` as the database host.

**Example:**

- `export PARTKEEPR_OKTOPART_APIKEY=`_your_api_key_
- `docker run -d -p 80:80 --network="host" -e PARTKEEPR_OKTOPART_APIKEY mhubig/partkeepr`
- open your browser on `http://localhost/setup`
- on the database setup page use `127.0.0.1` as the database host
- enjoy your running partkeepr!


I can at least confirm that this worked for me.


Sources: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

**Comment by christianlupus** [comment]
You did not make clear, if your SQL server is running in another docker container or on the host machine.
General rule of thumb: If you start using docker then completely stick with it. Do not mix up.

If you are running mysql on the host machine, @mindsolve gave you one option. An alternative would be to map the socket to the PartKeepr container (at the appropriate location) and use `locahost` instead (must be tested of course).

If you decide to go full in into docker, I suggest using `docker-compose`. This will allow you to have a separate bridge automatically configured per compose file. Think of it as a sub-LAN inside your host machine that does your work.
In this case the host of the db is neither `localhost` nor `127.0.0.1`, but the name of the db container. Docker should manage the rest and you should omit the `network=host` part then.

I will close this issue now, as there are solutions available. If you are still running into problems, feel free to write here, then I might reopen the issue.
