### ISSUE TITLE
Empty tips.json file

### ISSUE THREAD

**Issue by rphoover** [partkeepr/PartKeepr#1029]
Hello,

synctips is no longer working.

# System Information

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: N/A

$ wget https://partkeepr.org/tips.json
--2019-04-07 09:34:57--  https://partkeepr.org/tips.json
Resolving partkeepr.org (partkeepr.org)... 46.4.89.210, 2a01:4f8:140:72d5::2
Connecting to partkeepr.org (partkeepr.org)|46.4.89.210|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [application/json]
Saving to: \u2018tips.json\u2019

    [ <=>                                   ] 0           --.-K/s   in 0s      

2019-04-07 09:34:58 (0.00 B/s) - \u2018tips.json\u2019 saved [0/0]

# How to reproduce

Try wget https://partkeepr.org/tips.json and an empty file is returned.  This causes the partkeepr:cron:synctips method to fail.  Based on the crontab logs on my machine, this failure started on April 4th, 2019.  Prior to that, synctips worked.

**Comment by willbicks** [comment]
I'm afraid that PartKeepr is stuck in a bit of a holding pattern. Unfortunately the main (and for most purposes only) dev has left the project to focus on health issues, and things are kind of in limbo from my impression. I'm disappoined because so much work was put into this project and it is so so close to being complete, but I also completely understand that @Drachenkaetzchen has chosen to prioritize well-being. According to the most recent update on Patreon, @Drachenkaetzchen migrated the web hosting to a new server, and I'm guessing that's when the tips stopped working. That announcement, as well as the leaving the project one, are at https://www.patreon.com/partkeepr.

I'd be wiling to take on some of the website maintenance, wiki stuff, and other basic tasks, which I have experience with. Unfortunately I don't have enough of an understanding of the frameworks to do any development on the main project. I desperately want this project to continue and succeed, because it has so much promise, potential, and value.

Best of luck.

-Will Bicks

**Comment by rphoover** [comment]
It works now.  So, I am closing out this issue.
