### ISSUE TITLE
[Feature]Octopart -> OEMsecrets ?

### ISSUE THREAD

**Issue by BadamBoum** [partkeepr/PartKeepr#1030]
Hi !

I was a partsbox.io user and I'm now trying to migrate to PartKeepr for several reasons, mainly to use Android scan app (which need paid plan in partsbox). 
However, I had a.... surprise.... when I requested an Octopart API key and the guy answers me I have to pay monthly to access this API, lower plan is : $25/month up to 1,000 HTTP Requests per month (sic !). At this price, it's not far of partsbox fees...

So, two questions : 
* How are you doing ? Peoples here pay to have API access ? It sounds to be kind of racket to me...
* Does someone know OEMsecrets, already use its API or plan to do something with it ? It seems to be (really) free at the moment, but I only tried it in web browser, not through API.

Thank you,
Ben.

**Comment by willbicks** [comment]
I've been following the developments with the OctoPart API on a few other open source projects that rely on it. I am another recent partsbox convert, and I was equally surprised when I got a quote back from OctoPart. 

From other threads and admins who have had discussions with OctoPart, it sounds like they made this change permanently a few months ago. They suspended access for existing free API keys, and are pushing everyone over to their paid API plans, which are steep for us hobbyists. As far as I know, everyone has either had to stop using the API or pay their monthly pricing. It sounds like they might offer free APIs for those with .edu emails, but I don't know if anyone has actually tried to obtain one that way. It seems like OEM secrets is a okay alternative, although I worry whether they are going to go the same way as OctoPart, and start charging for API access. 

I don't want to be the guy who pretends to know everything and says the same thing over and over since I mentioned this in another issue thread #1029 , but I feel it could be helpful since I wasn't aware of this until recently. PartKeepr is kind of in a holding pattern since the main dev has left the project. I wrote more and linked to the announcement in that other thread. 

KiCost, another project that ran into [this issue](https://github.com/xesscorp/KiCost/issues/331), has discussed the possibility of integrating directly with distributor APIs, but this is a complicated task that doesn't seem likely given the current situation. It almost seems like a few of these projects that have been left in the dark by this change could band together and create a unified project for collecting this data, but I don't know if that will ever happen

As for me, I've just been inputting data manually. To a certain extent, I've found this to be better than the OctoPart integration on Partsbox, since it means I can have a much more consistent naming and numbering scheme. On partsbox, different passives were labeled differently, with different attribute fields, which meant that search and filtering wasn't particularly reliable. That being said, for other types of parts, being able to populate everything from a part no can be very valuable. 

Best of luck.

-Will

**Comment by BadamBoum** [comment]
Thank you Will for your quick and very extensive answer.

I had a look at KiCost and I see I had the same kind of answer than the guys here. IMHO, it's a way to kill open source and free apps like KiCost or PartKeepr at the benefit of "premium partners" like partsbox.

I'm also sad to see this project is in a sustaining state (and more to know main dev personal issues), but it seems enough mature to be used in this state, even without Octopart integration. As you said, it's hard to have a consistent naming with OP, while with a brain and a keyboard... It's quite easy :)

So, I'll definitely give a try to PartKeepr.

Thank you again Will.
Ben.

**Comment by JamesOctopart** [comment]
Hi all!

I work for Octopart and wanted to reach out as we are releasing a new version of our API with self service and a free tier for opensource users and this thread seemed to be an appropriate place to start.

We are planning on making 500 part request per month the volume for our free tier, does this sound to be enough to encompass most hobbyist users in PartKeepr?

**Comment by aarontc** [comment]
@JamesOctopart I don't speak for this project but this may be the wrong place for your thread. As for your question, when I go through a project design as a hobbyist, I often have an excess of 200 BOM parts, and often order alternates for prototyping stages, sometimes doubling or tripling the possible number of parts to investigate. For myself, a limit of 500 would be pretty tight.

**Comment by baradhili** [comment]
@JamesOctopart I've moved this to a new issue #1125
