### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by computergott** [partkeepr/PartKeepr#1035]
Hey,

I´ve installed Partkeeper 1.4.0 on my Debian 9 Server,

The install Path is /var/www/html/partkeeper. In /var/www/html/XXX is an other web app, so I didn´t change the Apache Web root.

The installation success but when I try to open http://IP-Adress/partkeeper/web/ I got a Error

It seems that your web-server misses the capability to parse .htaccess files or the Directory Index is misconfigured on nginx.

Any help?

Thanks!

**Comment by christianlupus** [comment]
OK, to be honest, I do not exactly get what you try to achieve and what you did.

You are running a machine with a webserver and another web app is already running successfully. Which webserver are you using (apache, nginx or some other)?
How is your webserver configured at the moment? What address do you need in order to access the other web service?

You do not need to change the webroot, there are other options in general. Can you link a site with the steps you took? There are also different ways to install partkeepr.

> It seems that your web-server misses the capability to parse .htaccess files or the Directory Index is misconfigured on nginx.
This is nonsense, sorry. Either you use apache (htaccess files) or nginx (and the directory index is part of the http server configuration, not of the web app).
To make things clear, partkeepr is a pure app solution that relies completely on a working infrastructure beneath.

**Comment by Drachenkaetzchen** [comment]
> This is nonsense, sorry.

Why would that be nonsense? Setup emits this message if it detects that the configuration does not work.

> It seems that your web-server misses the capability to parse .htaccess files or the Directory Index is misconfigured on nginx.

Didn't you click the link within the error window which leads to https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration ? Did you perform any configuration as outlined on the wiki page?

**Comment by christianlupus** [comment]
> Why would that be nonsense? Setup emits this message if it detects that the configuration does not work.

Ahh, I see. Sorry. I did not understand that this is the error message but the user's point of view.

**Comment by computergott** [comment]
Hey there,

I´ll close this ticket. Today I opened the Webpage from PartKeepr and it worked. Don´t ask why ;) 

I´ve done nothing since the installation (no Server reboot, no service restrart).

Greetings!
