### ISSUE TITLE
Time Zone error & Curl error

### ISSUE THREAD

**Issue by PranavS625** [partkeepr/PartKeepr#1107]
Using Ubuntu Server 18 & have installed Partkeepr 1.2.0 version.
I have installed following files - curl ntp mysql-server mysql-client php7.0 php7.0-apcu php7.0-apcu-bc php7.0-curl php7.0-gd php7.0-intl php7.0-ldap php7.0-mysql php7.0-dom php7.0-xml & apache2 apache2-doc

*problem* - while configuring - under prerequisites - Testing for correct PHP Settings I am getting two errors - 
1) Date.timezone must be test ------ in the php.ini file i have already changed the timezone to Asia/Kolkata

2) Curl Library not found. I have already installed curl. Still getting this error. 

Please help.

**Comment by christianlupus** [comment]
OK, just out of curiosity why do you did not go with the latest version?

OK, support for curl is there since version 0.76. The check since then was only modified minimally. Are you sure, curl is enabled in PHP not only installed?

Regarding the timezone setting: This is a Symfony requirement (a dependency from PartKeepr). I cannot tell you much where it was introduced. However, this should be set anyways.

I suggest that you **temporarily** add a file to show the php info page. Do you know how to do it? Then you see all enabled extensions (curl?) and the settings like the time zone.
You said that you already configured the time zone. Some distributions have multiple `php.ini` locations. Depending on the way, php is used (apache's mod_php, fpm, cli) different settings are applied. Maybe this is your problem.
