### ISSUE TITLE
PHP 7.1 only for now?

### ISSUE THREAD

**Issue by whc2001** [partkeepr/PartKeepr#1139]
I tried to install from git repository, but seems like it won't accept PHP 7.0 and PHP 7.2, but I am unable to get required packages installed for PHP 7.1 (I can find and install everything for 7.0/7.2, but not 7.1.). Is there any workaround, or I need to wait until new version? Thanks.

**Comment by christianlupus** [comment]
Short answer: Anything before 7.2 should do. So 7.0 should be fine. What happens if you try to install using 7.0?

**Comment by whc2001** [comment]
The installation wizard loads properly, but on the "Testing for PHP" step of Prerequisites page, it gives out an error about PHP version is too low, please use PHP 7.1 or above. Seems like PHP7.1 has been removed by many distribution for some reason, I can't even find the deb package for ldap module.

**Comment by christianlupus** [comment]
You can try the following: Go to [this file](https://github.com/partkeepr/PartKeepr/blob/master/web/setup/tests/check-php.php@L4) in your local environment. Replace the check for 7.1 by 7.0. Then you should be able to run it using PHP 7.0.

I thought, PHP 7.1 would be more probably be available than 7.0. The reason was to remove the 5.x branch of PHP support as this is highly outdated....

**Comment by whc2001** [comment]
Thanks, actually right after I posted this issue, I found a [docker script](https://github.com/mhubig/docker-partkeepr) that can install the entire PHP 7.1 environment for you, and after some fiddling I got it working. Since I have already made the instance running I decided not to try the code-modifying method, but I assume it works and you can use PHP 7.0.
