### ISSUE TITLE
Critical error after 30 seconds signed in

### ISSUE THREAD

**Issue by rochor** [partkeepr/PartKeepr#160]
Critical Error
# Details

The server returned a response which we were not able to interpret.
# Request

{"url":"rest.php/System/getSystemStatus","success":null,"failure":null,"method":"POST","params":"{}","headers":{"call":"getSystemStatus","lang":"en_US","session":"hgp7p3s6anh93ed5lpfqkqv4k6"}}
# Server Configuration

doctrine_orm_version: 2.2.1
doctrine_dbal_version: 2.2.1
doctrine_common_version: 2.2.1
php_version: 5.3.3-7+squeeze8
maxUploadSize: 33554432
availableImageFormats: 3FR,A,AI,ART,ARW,AVI,AVS,B,BGR,BGRA,BMP,BMP2,BMP3,BRF,BRG,C,CAL,CALS,CAPTION,CIN,CIP,CLIP,CMYK,CMYKA,CR2,CRW,CUR,CUT,DCM,DCR,DCX,DDS,DFONT,DJVU,DNG,DOT,DPX,EPDF,EPI,EPS,EPS2,EPS3,EPSF,EPSI,EPT,EPT2,EPT3,ERF,EXR,FAX,FITS,FRACTAL,FTS,G,G3,GBR,GIF,GIF87,GRADIENT,GRAY,GRB,GROUP4,HALD,HISTOGRAM,HRZ,HTM,HTML,ICB,ICO,ICON,INFO,INLINE,IPL,ISOBRL,J2C,JNG,JP2,JPC,JPEG,JPG,JPX,K,K25,KDC,LABEL,M,M2V,M4V,MAP,MAT,MATTE,MIFF,MNG,MONO,MOV,MP4,MPC,MPEG,MPG,MRW,MSL,MSVG,MTV,MVG,NEF,NULL,O,ORF,OTB,OTF,PAL,PALM,PAM,PATTERN,PBM,PCD,PCDS,PCL,PCT,PCX,PDB,PDF,PDFA,PEF,PES,PFA,PFB,PFM,PGM,PGX,PICON,PICT,PIX,PJPEG,PLASMA,PNG,PNG24,PNG32,PNG8,PNM,PPM,PREVIEW,PS,PS2,PS3,PSB,PSD,PTIF,PWP,R,RADIAL-GRADIENT,RAF,RAS,RBG,RGB,RGBA,RGBO,RLA,RLE,SCR,SCT,SFW,SGI,SHTML,SR2,SRF,STEGANO,SUN,SVG,SVGZ,TEXT,TGA,THUMBNAIL,TIFF,TIFF64,TILE,TIM,TTC,TTF,TXT,UBRL,UIL,UYVY,VDA,VICAR,VID,VIFF,VST,WBMP,WMF,WMV,WMZ,WPG,X,X3F,XBM,XC,XCF,XPM,XPS,XV,XWD,Y,YCbCr,YCbCrA,YUV

**Comment by clifcox** [comment]
Greetings,

I have the same problem using a fresh install of 1.2.0. Right after logging in I get not one but two Critical errors. The first one is:

POST http://pkr.eugenemakerspace.com/api/system_status

and the second is:

POST http://pkr.eugenemakerspace.com/api/user_preferences?_dc=1489354779589

Here is the full report of the latter:
`Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
POST http://pkr.eugenemakerspace.com/api/user_preferences?_dc=1489357249890

[object Object]

Response Status Code
==================================
200

Response
==================================
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
An Exception was thrown while handling: Internal Server Error

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.30-0+deb8u1
auto_start_session: true
maxUploadSize: 104857600
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
`
I set everything writable thusly:

`chown -R www-data.www-data partkeepr-1.2.0/
chmod -R ug+w partkeepr-1.2.0/
`
It seems to me that app.php should have been perpended to the path_info string by some rewrite rule. Perhaps this one?

`    # Rewrite all other queries to the front controller.
    RewriteRule .? %{ENV:BASE}/app.php [END]
`
Oh yeah, since I had Apache 2.4 I made the suggested change from [L] to [END]. Any ideas on this? :-)

    Thanks for a great project,
   Clif

**Comment by clifcox** [comment]
SOLVED! Ok, just took a bit to actually read the error. I updated /etc/php5/apache2/php.ini so that 
always_populate_raw_post_data = -1

and all the errors went away. :-)

   Thanks,
   Clif
