### ISSUE TITLE
use of Partkeepr for loan/swap/selling things

### ISSUE THREAD

**Issue by spanner888** [partkeepr/PartKeepr#242]
In addition to using Parkeepr for tracking parts & projects, I am looking at also using it for loan/swap/selling things. It would be really great to have ONE system in a space to track ALL these closely related things!

The basic additional features that can be managed in Partkeepr as is include:
    - can do loans (who has what + location) + history
    - ownership of things + change of ownership (swap/sell)

There are several ways different features could be implemented in the current system using categories, status, part parameters, projects, but they are a bit awkward. I am aware of other swap/loan systems and even got one suggestion from a question on the hackerspaces mailing list, but it really would be great to have all this in ONE system, so users only have one place to go!

So my question is - "Are others interested in having this ability added to Parkeepr?"
##

**Comment by evoltek** [comment]
This is a bit of an issue for me too, but mostly I would like @felicitus to review this database design limitation (the one he acknowledged in his comment) because I think it is hampering the use of Partkeepr for other, less narrow-focused, purposes. I know this is called Partkeepr after all, but the fact is that there are no other (suitable and uncomplicated) open-source stock control web-based applications, and Partkeepr could (should) fulfill that job nicely with just a bit a wider scope. I, for example, don't usually deal with generic electronic component parts: my "parts" are usually network cards, hard disks, transceivers, cables of various lengths and characteristics, whole servers or routers, even server racks and their components. Now, some of these can be represented in Partkeepr just fine, but most cannot because there's a distinguishing feature that they usually have and that Partkeepr has no notion of: identification. For example, a network card has a MAC address, a hard disk has a serial number, a server has an asset number (among other identifications), etc. Furthermore, these are sometimes stored at one storage location, but then they may get moved to a different storage, sometimes as a loan and sometimes not.

Ii think the difficulty with representing such situations in Partkeepr is due to the limitation @felicitus mentioned in the database design. I know that would not be easy to change, but I think it's well worth the effort because Partkeepr would be much more flexible then, able to be used in many more use-cases than now.

**Comment by DIYsciBorg** [comment]
evoltec:
Not saying the features should not implemented.. because they would be very handy..
But your requirements are fulfilled very well by another application built specifically for IT parts and equipment management. Take a look at GLPI and see if it does not fulfill your requirements immediately.

I want to see partkeepr grow. Not trying to push users away. But It IS built for one task, and built for that task VERY well.
Spreading out to make the system all inclusive has the possible risk of making it ineffective at its primary task (tracking high turn around, atomic, non serialized parts, and project inventory pulls)

**Comment by baradhili** [comment]
I'm going to close this as selling things would not be a use-case for an inventory.. better to use an ERP at least for that
