### ISSUE TITLE
BOM import

### ISSUE THREAD

**Issue by felicitus** [partkeepr/PartKeepr#416]
It would be useful to have a BOM import where you can upload an Excel or CSV bill of materials to check if any parts need to be orderd.
##

**Comment by dvatp** [comment]
Came here to add this feature request.  I see someone beat me to it.

I view this feature as a top priority, certainly above and beyond any supplier integration like Octopart, simply because most designers that I know (including me) use our design tools to select / import parts.  Then, when the design is ready to go to production we generate all of our outputs, including the BOM.

It would be awesome to be able to simply take that BOM in CSV format and add all of the parts to the database.  Then, assuming the default reorder rules are triggered, I could get a complete list of parts (not necessarily just for the current project) that I can order from my suppliers.

It would also be great to be able to export CSV for the current list of parts to be reordered as Digikey and others support CSV import and that would considerably simplify the ordering process.

**Comment by felicitus** [comment]
The import functionality is scheduled for Version 1.2 and can already be previewed on the demo syste. @dvatp can you check if it works for you?

**Comment by felicitus** [comment]
No feedback given for an extended period of time, closing the issue.

Feel free to re-open if you have additional information.
