### ISSUE TITLE
setup/js/wizard missing during setup

### ISSUE THREAD

**Issue by stepps** [partkeepr/PartKeepr#420]
I am trying to install from git, but the setup fails to find some files:

Tue Aug 04 11:35:28 2015] [error] [client 10.111.1.3] File does not exist: /var/www/html/PartKeepr/src/setup/extjs, referer: http://10.111.0.148/PartKeepr/src/setup/
[Tue Aug 04 11:35:28 2015] [error] [client 10.111.1.3] File does not exist: /var/www/html/PartKeepr/src/setup/js/wizard, referer: http://10.111.0.148/PartKeepr/src/setup/
[Tue Aug 04 11:35:29 2015] [error] [client 10.111.1.3] File does not exist: /var/www/html/PartKeepr/src/setup/js/wizard, referer: http://10.111.0.148/PartKeepr/src/setup/

I have also tried a developer install, clearing app/check.php end installing symfony and composer.

After clearing a few more dependency issues, when I run web/app.php I get:

The server returned a "500 Internal Server Error"

But nothing is logged in the apache logs

**Comment by felicitus** [comment]
Are you using the master branch or the sf2migration branch?

**Comment by stepps** [comment]
sf2migration. The master branch is missing the app/ folder, so I couldn clear check.php

**Comment by felicitus** [comment]
If you just want to use PartKeepr, please use the master branch for now. If you want to help with development, it would be best to step by in IRC so that I can give you instructions on how to getting started with the sf2migration branch. Be aware that the sf2migration branch doesn't contain a functional PartKeepr version yet.

**Comment by felicitus** [comment]
Can this issue be closed?
