### ISSUE TITLE
Project Report: Autofill

### ISSUE THREAD

**Issue by fulcrum3d** [partkeepr/PartKeepr#532]
Hi Felicitus,

in the previous issue, we discussed about adding a distributor to a Project Report in order to add the pricing. Unfortunately it doesn't and won't work.

Sadly the function Autofill is not working properly too.
Several prices are assigned right, most of them aren't. 
Can you please have a look at this function, as it would be the solution for our problem with adding a distributor. 

Regards, Frederik

**Comment by felicitus** [comment]
Can you elaborate what you mean with "assigned right, most aren't"?

I just tested Autofill on the demo system, it seems to work except for displaying the distributor name, which I'm about to fix.

**Comment by felicitus** [comment]
Thank you for the pull request. How can I reproduce the original issue?

**Comment by tinutac** [comment]
I've just noticed another problem with the autofill. The distributor is shown correctly but the distributor order number is wrong. I have a project for which I've created a report and autofill. The parts have the correct distributor numbers defined in the DB but in the report the distributor order number is wrong. The bug seems related to the part price: if the part price is the same then the order code is not updated. If the price changes then the order code is updated.

**Comment by felicitus** [comment]
If it's another problem, please create a separate issue for that.

**Comment by tinutac** [comment]
Hi @felicitus ,
Sorry for the late reply. I think we're talking about the same problem. 
> Sadly the function Autofill is not working properly too.
Several prices are assigned right, most of them aren't. 
Can you please have a look at this function, as it would be the solution for our problem with adding a distributor.


It seems, if you have two products with the same price, the distributor name/price is not updated anymore (until there's a price difference). I've just tested it on 0.79 (that contains the mod proposed by @fulcrum3d, if I'm correct) and it's still the same. I can add some screenshots to show it (or just create a small project with 2 parts of the same price and you should be able to reproduce it). 

I'm running partkeepr on my server (0.79) with the mod below in the autofill function and it seems to work correctly now. Since I'm not a contributor to the project, it would be great if one of you two could take a look at it, when you have some time and see if it's not a bugfix you could take into account.

```Javascript
	var partCount = this.reportResult.store.count();
	var cheapest;
	var cheapestPrice;
	var activeRecord;
	var activeDistributor;
	var currentPrice;
	var firstPositive;

        for (var i = 0; i < partCount; i++) {
            activeRecord = this.reportResult.store.getAt(i);
			firstPositive = true;
			cheapestPrice = 0;
			cheapest = null;

            for (var j = 0; j < activeRecord.getPart().distributors().count(); j++) {
                activeDistributor = activeRecord.getPart().distributors().getAt(j);
				currentPrice = parseFloat(activeDistributor.get("price"));
				
				if (currentPrice != 0)
				{
					if (firstPositive)
					{
						cheapestPrice = currentPrice;
						cheapest = activeDistributor;
						firstPositive = false;
					}
					else
					{
						if (currentPrice < cheapestPrice)
						{
							cheapestPrice = currentPrice;
							cheapest = activeDistributor;
						}
					}
				}
            }

            if (cheapest !== null) {
                activeRecord.setDistributor(cheapest.getDistributor());
                activeRecord.set("distributor_order_number", cheapest.get("orderNumber"));
                activeRecord.set("price", cheapest.get("price"));
                activeRecord.set("sum_order", activeRecord.get("missing") * activeRecord.get("price"));
                activeRecord.set("sum", activeRecord.get("quantity") * activeRecord.get("price"));
            }
        }
```

**Comment by felicitus** [comment]
I agree with the bugfix in the PR, will merge
