### ISSUE TITLE
'Save' button on part editing popup isn't always enabled

### ISSUE THREAD

**Issue by agamez** [partkeepr/PartKeepr#546]
At least on Firefox 38.3.0, the following happens:

Create a new part, mark 'Create blank item after save', and save that part. The popup remains open to create a new part, but the 'Save' button is disabled, and is kept this way until a non determined time or action occurs, after which it gets enabled again.

**Comment by felicitus** [comment]
I can confirm the issue, it's reproducible on the demo system. The save button gets re-enabled after 30 seconds, which usually only occur when an error while saving occurs.

**Comment by felicitus** [comment]
The issue should now be solved, can you test if it works for you (demo system)?

**Comment by agamez** [comment]
I can confirm it's now fixed. Whatever you've done seems to have fixed #545 too. Does it make sense?

**Comment by felicitus** [comment]
yes that could be the case, since layout errors can occur when a js error occurs. 

Am 24. Dezember 2015 17:26:26 MEZ, schrieb "Alvaro G. M." <notifications@github.com>:
>I can confirm it's now fixed. Whatever you've done seems to have fixed
>#545 too. Does it make sense?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/partkeepr/PartKeepr/issues/546#issuecomment-167132952

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
