### ISSUE TITLE
Printing plugin support disappered in 0.82

### ISSUE THREAD

**Issue by andrew-xdn** [partkeepr/PartKeepr#622]
Can't embed my label printing system due to lack of printing plugins support on 0.82. :(

**Comment by felicitus** [comment]
The printing code was removed with 0.75 since the original author couldn't be contacted and honestly I didn't understand the code and functionality, so I couldn't maintain it. 

The printing functionality won't come back in the original form. There's nothing I can do about it, but you can help by specifying what functionality you expect from printing.

**Comment by andrew-xdn** [comment]
Got the problem. I'll develop a standalone script as a temporal solution. Then I'll be able to look forward for the integration.

**Comment by ely-az** [comment]
This is really bad news! I need to be able to print bin labels or this whole inventory system is useless to us. Is there no hope for printing in the future? We would be happy to help with coding and/or fund development of the printing feature. Please let me know where you are in the development.

**Comment by felicitus** [comment]
As a quick solution, I recommend to downgrade to 0.19 if you need printing in production. For further development I can refer to issue #21 but of course sponsored development would be possible. You can find contact information on the partkeepr website.
