### ISSUE TITLE
Feature Request: Frontend for customers

### ISSUE THREAD

**Issue by agardim** [partkeepr/PartKeepr#692]
We use partkeepr to organize our electronic components storage and it's very usefull.
But everytime out customers need some part they need to call or e-mail us so we can check if available and how much is it.
It would be very interesting if PartKeepr have a Frontend interface where our customers can sign in and online check all available electronic components and check the retail price.

**Comment by felicitus** [comment]
I believe this is a very use-case specific feature. You should be able to implement it on your own by using the API. I'll leave the feature request open, but it will probably take a very long time to be implemented.

**Comment by agardim** [comment]
If you know someone that can implement it please send me the contact (e-mail) so I can ask about price to do it. Here I don´t know anyone who can do it.

**Comment by felicitus** [comment]
@agardim the PartKeepr UG can provide that, see https://partkeepr.com/support/commercial

**Comment by brads4** [comment]
I'm pretty far engaged in writing an API client for Partkeepr, which I will use to keep all my sales channels in sync, including online web store, ebay, amazon, etc, including hooks to adjust data when sales occur.  This is a more useful solution than a proprietary store front end IMO.  You can hook into a wide range of technology using this approach.

**Comment by brads4** [comment]
I've got my Partkeepr API client now working, and interacting with the REST webservices, which is the majority of the battle behind me.

- Written in Java using OpenFeign to access and describe the Partkeepr API.
- WSSE Digest Authentication interceptor in the Partkeepr style
- Uses Annotated POJOS to access data, serialised via jackson (other options available)

There's a lot more work to do, but I envision this is a component that is used to integrate into a more robust service gate, which handles more complex tasks, utilising this component piece in more complex service routes.


Some issues I had:
- Problems with hard coded paths. If you use a context path, like I do prepare to have a bad time.
- There were redirect issues with the configuration, so keep that in mind.
- JSONLD - this was not so much a problem but a learning curve associated with JSON-LD/Hydra style linked data apis. 
- No way to discover actual endpoint paths: it took a long time to get at the API endpoints(they are different than the documented element paths.  They are similar to the Object type, but usually different.. example "storageLocation" API endpoint maps to "storage_locations".


I'm not sure the best way to share this, but I can expose the OpenFeign Partkeepr API probably as a github project. Sorry it's not PHP, but I don't like PHP it turns out :)

**Comment by baradhili** [comment]
We really need a way to have plugins, or to at least list stuff people have done..

**Comment by christianlupus** [comment]
see also #531
