### ISSUE TITLE
Parameters tab disappered from item windows

### ISSUE THREAD

**Issue by andrew-xdn** [partkeepr/PartKeepr#728]
The tab "Parameters" has disappeared in the last release. Why? It was really useful. Anyway, now I should write a script to transfer all parameters into desription field. Is there an another solution for this problem?

**Comment by felicitus** [comment]
The part parameters were removed since there were several bugs which prevented proper input of part parameters, as a consequence the parameters tab has been removed until the bugs are fixed. I'm sorry for the issue, and I plan to bring it back ASAP. If you require the parameters, I suggest you downgrade to a previous version.

**Comment by woodworker** [comment]
Is this related to #512 ?
Is there a way to help? Are the needed/wanted changes for the refactoring written down somewhere?

**Comment by felicitus** [comment]
Yes, that's correct. No, currently specification has been created due to the lack of time so far, however, it might be that this will be implemented very soon.

**Comment by felicitus** [comment]
The next version includes the refactored part parameters as seen on demo.partkeepr.org - closing.

**Comment by andrew-xdn** [comment]
Thanks! Great job!
