### ISSUE TITLE
misses the capability to parse .htaccess files or the Directory...

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#783]
I have a dedicated server for partkeepr. Have been using it for about one year with no problems. Today I got blank screen when trying to enter the partkeepr. When I write /index.html i get the message:

It seems that your web-server misses the capability to parse .htaccess files or the Directory Index is misconfigured on nginx.
Please read the KB article on PartKeepr web server configuration. 

Im using Apache with mysql, not nginx. How could this happen suddenly?

(im not logging in to the server so often, now I have forgotten the root password, working on it to see the php log)

EDIT: Now im in. I can run the /setup/ without problem. But still the login page never shows.

**Comment by adis1987** [comment]
Uploaded new version of partkeepr (1.1.0), did /setup/ and restarted the apache. Now it works.

**Comment by felicitus** [comment]
I'm glad that it works for you now, may I close the issue?

**Comment by adis1987** [comment]
Yes :)

**Comment by mixosp** [comment]
I am a new user here trying to install the Partkeepr on my server. I upload and unzip the files and point my browser to https://www.test-domain.com/bom/web/ to start the installation but I get this:

_It seems that your web-server misses the capability to parse .htaccess files or the Directory Index is misconfigured on nginx.
Please read the KB article on PartKeepr web server configuration._

I tried to follow the quide on [wiki](https://wiki.partkeepr.org/wiki/KB00005:Web_Server_Configuration), but no luck.

Any direction on this would be much appreciated.

**Comment by christianlupus** [comment]
@mixosp This issue is closed almost 2 years ago. So please open a new issue, if this still persists to keep the discussion separate.

Quick question: Did you run the setup (aka visit the `/setup/` folder)? This is necessary before the main app can work. If you open a new issue, please provide us with the basic information, what *exactly* did you do, what OS, http server, PHP and DB version you are running, which version (release vs git) you try to install. Thankl you.
