### ISSUE TITLE
Missing webserver-test

### ISSUE THREAD

**Issue by Gasman2014** [partkeepr/PartKeepr#806]
Webserver setup fails at 'Testing webserver rewrite capability'

The error reports no `Partkeepr/web/setup/webserver-test` file (which, indeed is not present)

![screen shot 2017-02-01 at 22 03 16](https://cloud.githubusercontent.com/assets/8401593/22528258/5ec82fe0-e8ca-11e6-81bd-c323c858c1fc.png)

```
$ ls web/setup
css        images     index.html js         tests

$ ls web/setup/tests/
check-php-prerequisites.php check-php.php               check.php                   webservercheck.json
```

**Comment by felicitus** [comment]
This is absolutely correct, since you need to configure your server to allow rewriting URLs. The link within the error details shows you what needs to be configured.

For Apache, the supplied [.htaccess](https://github.com/partkeepr/PartKeepr/blob/master/web/.htaccess#L19) file takes care of the check, for nginx you need to configure it yourself.

**Comment by Gasman2014** [comment]
OK, got it. Thanks.
