### ISSUE TITLE
PartKeepr with additional nginx basic auth

### ISSUE THREAD

**Issue by kubudubu** [partkeepr/PartKeepr#975]
Hi,
I'm trying to configure PartKeepr behind another authentication layer. What I wanted to do is to just setup nginx basic authentication. However, it results in "Invalid username/password" window message. Is it possible to configure nginx basic auth that way to work properly with internal app authentication?
I'm using WSSE authentication in PartKeepr. It looks like nginx basic auth is interferring somehow with app authentication. Can you help, plz?

# System Information
* PartKeepr Version: (based on one of the lastest commits: 7dd3ef8)

# How to reproduce
1) Setup nginx basic auth in `location \` :
`auth_basic "Restricted Content";
  auth_basic_user_file /etc/nginx/.htpasswd; `
2) Try to log in with proper credentials

**Comment by Drachenkaetzchen** [comment]
I'm absolutely not sure if this will work. You'd have to research this yourself; especially if WSSE uses similar headers as HTTP Basic. 

Additionally, WSSE will be faded out in one of the upcoming releases as it is not maintained by the Symfony2 package we use and it gave many problems in the past due to time zone differences.

I think the starting point would be to inspect the Symfony2 authentication framework as well as the corresponding WSSE package.

**Comment by Drachenkaetzchen** [comment]
Please note that the GitHub issue tracker is reserved for bug reports and feature requests. It is not a support forum - for community support, please refer to https://partkeepr.com/support/
